### ISSUE TITLE
Forms to manage groups permissions in the platform

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#760]

**Comment by burnettk** [comment]
would you imagine the form causing the DMN file to be updated? if not, how would the system "remember" that the new group permission (for example) was supposed to exist, so it wouldn't be deleted the next time set-permissions was run?

**Comment by harmeet-status** [comment]
Yes the form which would be part of a new update permission process models, would be able to update the DMN table, so that we can manage the DMN table from the form itself.

**Comment by danfunk** [comment]
Recommend implementing this with Data Stores which are implemented already, but require UI.
All told this is 7 days - stretched across the following tickets, that would provide enough functionality that the Data Store could replace the DMN table as the means of managing permissions.  

- [ ] Edit updated rows for Data Stores (CRUD) ticket [Ticket 646](https://github.com/sartography/spiff-arena/issues/646) - 2 days
- [ ] Search/Sort/Filter UI Work for the Data Stores interface [Ticket 646](https://github.com/sartography/spiff-arena/issues/646) - 2 Days
- [ ] Modeller support for Data Stores [Ticket 549](https://github.com/sartography/spiff-arena/issues/549) (2.5 days)
- [ ] BPMN to convert a DMN to a Data Store (.5 day)

**Comment by harmeet-status** [comment]
@danfunk we discussed that we would have 2 types of datastore
1. Seeded by process model, cannot be changed after this (read-only)
2. Similar to the DB where we would update values using process models

We would use no. 2 for permissions. @danfunk is this correct?

**Comment by burnettk** [comment]
it is not explicitly stated on this ticket about the desire to be able to edit permissions directly in prod outside of source control. but that desire exists, right? we want to make sure we are designing a solution that satisfies the constraints, because we can definitely add forms without making things directly editable in prod (which would be a smaller change), but we don't want to do that if it doesn't solve the problem that this ticket was filed to address.

**Comment by harmeet-status** [comment]
We definitely want to edit permissions in Prod directly, without source control.

**Comment by burnettk** [comment]
Thanks. That does make me want to ask, “why?” I assume the answer is because it takes too long, involves too many steps, requires approvals, etc. we might separately try to address these issues, since they affect everything that Sasha and Marius do, not just permissions.

However, the simplest solution that satisfies that requirement is to remove the version controlled permissions files (currently two dmn files per environment), and just have users manage permissions through forms that edit the database directly. The biggest issues with this are lack of traceability (who broke prod and when?) and the inability to create environments from scratch in an automated fashion. These issues might push us towards some sort of a hybrid solution that is part version control and part live edited database data. Whoever comes up with a proposal that addresses all of the requirements and constraints gets a cake.

**Comment by harmeet-status** [comment]
Editing forms would work, provided that we have a way to specifying at the command line, the ability to run a seed process model to setup the base permissions when deploying onto a new environment. Some parameters we can pass through.

Otherwise all run instances of the process model will be run by a logged in user, so we can have full traceability. Doesn't this solve all the problems? How could prod break, while applying permissions?

**Comment by danfunk** [comment]
### Some high level groups are set during Deployment of the instance
* Base Administrative User Assignments - YAML file that is part of the deployment

### Groups to Permissions are mostly stored in Git ( These are defined in a DMN Table or Json File Store)
* User Groups to Permissions

### Production Specific Permissions - stored in a Local Data Store
* User Assignment to Groups - Local Data Store instance specific

Basically as a first pass, we alter the BPMN permissions process to allow you to add additional users to a group. 

The process model could include a form:
* type ahead for a user  (possibly set this up as a repeating section in the form)
* dropdown for group assignment

- this saves this to the data store which can be viewed and modified from the datastore view as well.  So you can edit the data store, and then re-run the permissions process.
